### ISSUE TITLE
Some errors in the log

### ISSUE THREAD

**Issue by robehem** [alexanderwink/kiauvoeurope#1]
I was happy to find this integration but unfortunately it doesn't work for me. I got the following in the log running 2021.2.2:

```
Logger: homeassistant.helpers.integration_platform
Source: loader.py:480 
First occurred: 18:15:45 (3 occurrences) 
Last logged: 18:15:45

Unexpected error importing kiauvoeurope/logbook.py
Unexpected error importing kiauvoeurope/media_source.py
Unexpected error importing kiauvoeurope/system_health.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 475, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 480, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.kiauvoeurope-master.logbook'
```

and also:
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:126 
Integration: Sensor (documentation, issues) 
First occurred: 18:15:48 (1 occurrences) 
Last logged: 18:15:48

The kiauvoeurope platform for the sensor integration does not support platform setup. Please remove it from your config.
```

**Comment by robehem** [comment]
Now I was to quick! I see the percentage now, I guess I had to wait a while. It still would be nice to not see the above error messages though :-)
